### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dignifiedquire** [dignifiedquire/dc40#3]
# DC40 Roadmap 
 
## Milestone 1 
> Goal: Increase number of users to > 1
 

- [ ] Attach files
- [x] Account Setup
- [x] Account switching 
- [x] Use new core api for account management
- [ ] Context menu for message
  - Start chat (contact requests)
  - Show message info
- [ ] download files
- [x] message status indicators
- [ ] Create chat
  - contact list
- [x] proper refresh
- [ ] minimal Chat details
- [ ] minimal account settings

## Milestone 1.5 
> Goal: Onboard more devs

- [ ] improve code documentation
- [x] restructure crates
- [ ] document architecture
- [ ] setup style-compoment structure

## Milestone 2 
> Goal: MVP

- [ ] Bubble view 
- [ ] Search
- [ ] background images
- [ ] inline video + audio player
- [ ] native notifications
- [ ] send voice messages
- [ ] emoji selector, 
- [ ] cross platform emoji display
- [ ] Chat details
  - image/files gallery
- [ ] qr code management
- [ ] account settings  
- [ ] script based packaging and building 
- [ ] setup and integrate i18n

## Future future

- [ ] location map
